In [3]:
import numpy as np 
import pandas as pd


Two- dimensional array

In [4]:
A=np.array([[23,34,5],[23,3,4],[3,4,1]])
A

array([[23, 34,  5],
       [23,  3,  4],
       [ 3,  4,  1]])

In [13]:
C=print("the sum of 2D=",np.sum(A))

the sum of 2D= 100


minimum value

In [14]:
np.min(A)

1

maximum value 

In [15]:
np.max(A)

34

50 percentile

In [17]:
np.percentile(A,50)

4.0

In [19]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Access all the elements of array except first one

In [20]:
arr[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Sum of addition 

In [21]:
A=np.array([[23,34,5],[23,3,4],[3,4,1]])
A

array([[23, 34,  5],
       [23,  3,  4],
       [ 3,  4,  1]])

In [22]:
B=np.array([[32,4,15],[3,13,40],[13,34,21]])
B

array([[32,  4, 15],
       [ 3, 13, 40],
       [13, 34, 21]])

In [23]:
A+B

array([[55, 38, 20],
       [26, 16, 44],
       [16, 38, 22]])

Returns all elements 

In [24]:
a=pd.Series([1,2,3,4,1,3,3,4,1,3,4,1,3,4])
a

0     1
1     2
2     3
3     4
4     1
5     3
6     3
7     4
8     1
9     3
10    4
11    1
12    3
13    4
dtype: int64

Print first three elementof the series 

In [26]:
print(a[:3])

0    1
1    2
2    3
dtype: int64


Print last element

In [28]:
print(a[-1:])

13    4
dtype: int64


Return last elements except last two elements 

In [30]:
print(a[:-2])

0     1
1     2
2     3
3     4
4     1
5     3
6     3
7     4
8     1
9     3
10    4
11    1
dtype: int64


Print elements except last element 

In [31]:
print(a[:-1])

0     1
1     2
2     3
3     4
4     1
5     3
6     3
7     4
8     1
9     3
10    4
11    1
12    3
dtype: int64


# returns last two elements

In [34]:
print(a[-2:])

12    3
13    4
dtype: int64
